### ISSUE TITLE
(Caused by SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'minikubeCA', 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost'",

### ISSUE THREAD

**Issue by marcellodesales** [karmab/samplecontroller#1]
* Can't get the CRD container to bootstrap.
* Just ran the commands from the README

```
Every 2.0s: kubectl get pods                                                  sdgl1508ac95f.lan: Fri Mar  9 02:06:37 2018

NAME                                  READY     STATUS    RESTARTS   AGE
paas-app-controller-dcb9bd6c5-gjqrn   1/1       Running   1          8h
samplecontroller-856d6db78-zhxbl      0/1       Error     2          27s
sampleui-b8866c764-wmpm6              1/1       Running   0          8m
```

# Pod Logs

```
$ kubectl logs samplecontroller-856d6db78-p25zf
2018-03-09 10:01:57,801 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subjectAltName': (('DNS', 'minikubeCA'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.101'), ('IP Address', '10.96.0.1'), ('IP Address', '10.0.0.1')), 'notBefore': u'Mar  8 19:16:42 2018 GMT', 'serialNumber': u'02', 'notAfter': 'Mar  8 19:16:42 2019 GMT', 'version': 3L, 'subject': ((('organizationName', u'system:masters'),), (('commonName', u'minikube'),)), 'issuer': ((('commonName', u'minikubeCA'),),)}
2018-03-09 10:01:57,802 WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'minikubeCA', 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost'",),)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
2018-03-09 10:01:57,807 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subjectAltName': (('DNS', 'minikubeCA'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.101'), ('IP Address', '10.96.0.1'), ('IP Address', '10.0.0.1')), 'notBefore': u'Mar  8 19:16:42 2018 GMT', 'serialNumber': u'02', 'notAfter': 'Mar  8 19:16:42 2019 GMT', 'version': 3L, 'subject': ((('organizationName', u'system:masters'),), (('commonName', u'minikube'),)), 'issuer': ((('commonName', u'minikubeCA'),),)}
2018-03-09 10:01:57,808 WARNING Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'minikubeCA', 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost'",),)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
2018-03-09 10:01:57,814 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subjectAltName': (('DNS', 'minikubeCA'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.101'), ('IP Address', '10.96.0.1'), ('IP Address', '10.0.0.1')), 'notBefore': u'Mar  8 19:16:42 2018 GMT', 'serialNumber': u'02', 'notAfter': 'Mar  8 19:16:42 2019 GMT', 'version': 3L, 'subject': ((('organizationName', u'system:masters'),), (('commonName', u'minikube'),)), 'issuer': ((('commonName', u'minikubeCA'),),)}
2018-03-09 10:01:57,814 WARNING Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'minikubeCA', 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost'",),)': /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions
2018-03-09 10:01:57,819 ERROR Certificate did not match expected hostname: 10.96.0.1. Certificate: {'subjectAltName': (('DNS', 'minikubeCA'), ('DNS', 'kubernetes.default.svc.cluster.local'), ('DNS', 'kubernetes.default.svc'), ('DNS', 'kubernetes.default'), ('DNS', 'kubernetes'), ('DNS', 'localhost'), ('IP Address', '192.168.99.101'), ('IP Address', '10.96.0.1'), ('IP Address', '10.0.0.1')), 'notBefore': u'Mar  8 19:16:42 2018 GMT', 'serialNumber': u'02', 'notAfter': 'Mar  8 19:16:42 2019 GMT', 'version': 3L, 'subject': ((('organizationName', u'system:masters'),), (('commonName', u'minikube'),)), 'issuer': ((('commonName', u'minikubeCA'),),)}
Traceback (most recent call last):
  File "/tmp/controller.py", line 40, in <module>
    current_crds = [x['spec']['names']['kind'].lower() for x in v1.list_custom_resource_definition().to_dict()['items']]
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/apiextensions_v1beta1_api.py", line 496, in list_custom_resource_definition
    (data) = self.list_custom_resource_definition_with_http_info(**kwargs)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/apis/apiextensions_v1beta1_api.py", line 593, in list_custom_resource_definition_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 321, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 155, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/api_client.py", line 342, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 231, in GET
    query_params=query_params)
  File "/usr/lib/python2.7/site-packages/kubernetes/client/rest.py", line 205, in request
    headers=headers)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/poolmanager.py", line 321, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 668, in urlopen
    **response_kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python2.7/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.96.0.1', port=443): Max retries exceeded with url: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions (Caused by SSLError(CertificateError("hostname '10.96.0.1' doesn't match either of 'minikubeCA', 'kubernetes.default.svc.cluster.local', 'kubernetes.default.svc', 'kubernetes.default', 'kubernetes', 'localhost'",),))

```

# Services running

```
Every 2.0s: kubectl get services                sdgl1508ac95f.lan: Fri Mar  9 02:03:57 2018

NAME         TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes   ClusterIP      10.96.0.1       <none>        443/TCP          14h
sampleui     LoadBalancer   10.109.52.254   <pending>     9000:31419/TCP   5m
```

**Comment by karmab** [comment]
you are right, marcello, this happens specifically when running on minikube, from what i see

**Comment by aogier** [comment]
Hello I think we could solve this one as per #2 can you please confirm ? Regards

**Comment by karmab** [comment]
fixed in https://github.com/karmab/samplecontroller/commit/6b9c9b8c5e74b30ba63e88efbfbb434cc7634af5 indeed ! thanks @aogier

**Comment by ltdonglei** [comment]
config.load_kube_config()
c = Configuration()
c.assert_hostname = False
Configuration.set_default(c)
api = core_v1_api.CoreV1Api()
